# Generated by Django 6.0.7 on 2026-07-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.DurationField(help_text='Format: MM:SS or HH:MM:SS'),
        ),
    ]
