# Generated by Django 6.0.7 on 2026-08-04 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_song_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='moods/')),
                ('mood_type', models.CharField(choices=[('Happy', 'Happy'), ('Sad', 'Sad'), ('Energetic', 'Energetic'), ('Relaxed', 'Relaxed'), ('Romantic', 'Romantic'), ('Party', 'Party'), ('Workout', 'Workout'), ('Chill', 'Chill'), ('Focus', 'Focus'), ('Sleep', 'Sleep'), ('Travel', 'Travel'), ('Study', 'Study'), ('Motivation', 'Motivation'), ('Gaming', 'Gaming'), ('Meditation', 'Meditation')], max_length=20, unique=True)),
                ('description', models.CharField(blank=True, help_text='Optional description for the mood.', max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='mood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.mood'),
        ),
    ]
